/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import games.mythical.ivi.sdk.model.BitPayTokenDto;
import games.mythical.ivi.sdk.model.BraintreeTokenDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClientPaymentTokenDto
 */
public class ClientPaymentTokenDtoTest {
    private final ClientPaymentTokenDto model = new ClientPaymentTokenDto();

    /**
     * Model tests for ClientPaymentTokenDto
     */
    @Test
    public void testClientPaymentTokenDto() {
        // TODO: test ClientPaymentTokenDto
    }

    /**
     * Test the property 'braintree'
     */
    @Test
    public void braintreeTest() {
        // TODO: test braintree
    }

    /**
     * Test the property 'bitpay'
     */
    @Test
    public void bitpayTest() {
        // TODO: test bitpay
    }

}
