/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreatePaymentMethodRequest
 */
public class CreatePaymentMethodRequestTest {
    private final CreatePaymentMethodRequest model = new CreatePaymentMethodRequest();

    /**
     * Model tests for CreatePaymentMethodRequest
     */
    @Test
    public void testCreatePaymentMethodRequest() {
        // TODO: test CreatePaymentMethodRequest
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'paymentMethodNonce'
     */
    @Test
    public void paymentMethodNonceTest() {
        // TODO: test paymentMethodNonce
    }

}
