/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListSaleRequest
 */
public class ListSaleRequestTest {
    private final ListSaleRequest model = new ListSaleRequest();

    /**
     * Model tests for ListSaleRequest
     */
    @Test
    public void testListSaleRequest() {
        // TODO: test ListSaleRequest
    }

    /**
     * Test the property 'sellerProceeds'
     */
    @Test
    public void sellerProceedsTest() {
        // TODO: test sellerProceeds
    }

    /**
     * Test the property 'ownerPlayerId'
     */
    @Test
    public void ownerPlayerIdTest() {
        // TODO: test ownerPlayerId
    }

    /**
     * Test the property 'sellByDays'
     */
    @Test
    public void sellByDaysTest() {
        // TODO: test sellByDays
    }

    /**
     * Test the property 'gameInventoryIds'
     */
    @Test
    public void gameInventoryIdsTest() {
        // TODO: test gameInventoryIds
    }

    /**
     * Test the property 'saleModel'
     */
    @Test
    public void saleModelTest() {
        // TODO: test saleModel
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
