/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MarketplaceItemDto
 */
public class MarketplaceItemDtoTest {
    private final MarketplaceItemDto model = new MarketplaceItemDto();

    /**
     * Model tests for MarketplaceItemDto
     */
    @Test
    public void testMarketplaceItemDto() {
        // TODO: test MarketplaceItemDto
    }

    /**
     * Test the property 'dgoodsMetadata'
     */
    @Test
    public void dgoodsMetadataTest() {
        // TODO: test dgoodsMetadata
    }

    /**
     * Test the property 'imageLargeUrl'
     */
    @Test
    public void imageLargeUrlTest() {
        // TODO: test imageLargeUrl
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'tokenName'
     */
    @Test
    public void tokenNameTest() {
        // TODO: test tokenName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'listingId'
     */
    @Test
    public void listingIdTest() {
        // TODO: test listingId
    }

    /**
     * Test the property 'imageSmallUrl'
     */
    @Test
    public void imageSmallUrlTest() {
        // TODO: test imageSmallUrl
    }

    /**
     * Test the property 'metadataUri'
     */
    @Test
    public void metadataUriTest() {
        // TODO: test metadataUri
    }

    /**
     * Test the property 'gameInventoryId'
     */
    @Test
    public void gameInventoryIdTest() {
        // TODO: test gameInventoryId
    }

    /**
     * Test the property 'ownerMythicalId'
     */
    @Test
    public void ownerMythicalIdTest() {
        // TODO: test ownerMythicalId
    }

    /**
     * Test the property 'finalized'
     */
    @Test
    public void finalizedTest() {
        // TODO: test finalized
    }

    /**
     * Test the property 'itemName'
     */
    @Test
    public void itemNameTest() {
        // TODO: test itemName
    }

    /**
     * Test the property 'ownerPlayerId'
     */
    @Test
    public void ownerPlayerIdTest() {
        // TODO: test ownerPlayerId
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'render'
     */
    @Test
    public void renderTest() {
        // TODO: test render
    }

    /**
     * Test the property 'dgoodId'
     */
    @Test
    public void dgoodIdTest() {
        // TODO: test dgoodId
    }

}
