/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SalesTaxInfoDto
 */
public class SalesTaxInfoDtoTest {
    private final SalesTaxInfoDto model = new SalesTaxInfoDto();

    /**
     * Model tests for SalesTaxInfoDto
     */
    @Test
    public void testSalesTaxInfoDto() {
        // TODO: test SalesTaxInfoDto
    }

    /**
     * Test the property 'zip'
     */
    @Test
    public void zipTest() {
        // TODO: test zip
    }

    /**
     * Test the property 'countyRate'
     */
    @Test
    public void countyRateTest() {
        // TODO: test countyRate
    }

    /**
     * Test the property 'combinedTaxRate'
     */
    @Test
    public void combinedTaxRateTest() {
        // TODO: test combinedTaxRate
    }

    /**
     * Test the property 'combinedDistrictRate'
     */
    @Test
    public void combinedDistrictRateTest() {
        // TODO: test combinedDistrictRate
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'county'
     */
    @Test
    public void countyTest() {
        // TODO: test county
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateRate'
     */
    @Test
    public void stateRateTest() {
        // TODO: test stateRate
    }

    /**
     * Test the property 'exempt'
     */
    @Test
    public void exemptTest() {
        // TODO: test exempt
    }

    /**
     * Test the property 'cityRate'
     */
    @Test
    public void cityRateTest() {
        // TODO: test cityRate
    }

}
