/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import games.mythical.ivi.sdk.model.ElasticDgood;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchHit
 */
public class SearchHitTest {
    private final SearchHit model = new SearchHit();

    /**
     * Model tests for SearchHit
     */
    @Test
    public void testSearchHit() {
        // TODO: test SearchHit
    }

    /**
     * Test the property 'getIndex'
     */
    @Test
    public void getIndexTest() {
        // TODO: test getIndex
    }

    /**
     * Test the property 'getSource'
     */
    @Test
    public void getSourceTest() {
        // TODO: test getSource
    }

    /**
     * Test the property 'getType'
     */
    @Test
    public void getTypeTest() {
        // TODO: test getType
    }

    /**
     * Test the property 'getScore'
     */
    @Test
    public void getScoreTest() {
        // TODO: test getScore
    }

    /**
     * Test the property 'getId'
     */
    @Test
    public void getIdTest() {
        // TODO: test getId
    }

}
