/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransferItemRequest
 */
public class TransferItemRequestTest {
    private final TransferItemRequest model = new TransferItemRequest();

    /**
     * Model tests for TransferItemRequest
     */
    @Test
    public void testTransferItemRequest() {
        // TODO: test TransferItemRequest
    }

    /**
     * Test the property 'destPlayerId'
     */
    @Test
    public void destPlayerIdTest() {
        // TODO: test destPlayerId
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'sourcePlayerId'
     */
    @Test
    public void sourcePlayerIdTest() {
        // TODO: test sourcePlayerId
    }

    /**
     * Test the property 'newGameInventoryId'
     */
    @Test
    public void newGameInventoryIdTest() {
        // TODO: test newGameInventoryId
    }

    /**
     * Test the property 'gameInventoryId'
     */
    @Test
    public void gameInventoryIdTest() {
        // TODO: test gameInventoryId
    }

}
