/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateMetadataRequest
 */
public class UpdateMetadataRequestTest {
    private final UpdateMetadataRequest model = new UpdateMetadataRequest();

    /**
     * Model tests for UpdateMetadataRequest
     */
    @Test
    public void testUpdateMetadataRequest() {
        // TODO: test UpdateMetadataRequest
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'authenticity'
     */
    @Test
    public void authenticityTest() {
        // TODO: test authenticity
    }

    /**
     * Test the property 'imageSmall'
     */
    @Test
    public void imageSmallTest() {
        // TODO: test imageSmall
    }

    /**
     * Test the property 'tokenName'
     */
    @Test
    public void tokenNameTest() {
        // TODO: test tokenName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'imageLarge'
     */
    @Test
    public void imageLargeTest() {
        // TODO: test imageLarge
    }

    /**
     * Test the property 'render'
     */
    @Test
    public void renderTest() {
        // TODO: test render
    }

    /**
     * Test the property 'dgoodId'
     */
    @Test
    public void dgoodIdTest() {
        // TODO: test dgoodId
    }

}
