/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import games.mythical.ivi.sdk.model.CallbackData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BurnItemCallbackRequest
 */
@JsonPropertyOrder({
  BurnItemCallbackRequest.JSON_PROPERTY_CALLBACK,
  BurnItemCallbackRequest.JSON_PROPERTY_GAME_INVENTORY_ID
})
@JsonTypeName("BurnItemCallbackRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BurnItemCallbackRequest {
  public static final String JSON_PROPERTY_CALLBACK = "callback";
  private CallbackData callback;

  public static final String JSON_PROPERTY_GAME_INVENTORY_ID = "gameInventoryId";
  private String gameInventoryId;


  public BurnItemCallbackRequest callback(CallbackData callback) {
    
    this.callback = callback;
    return this;
  }

   /**
   * Get callback
   * @return callback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CallbackData getCallback() {
    return callback;
  }


  public void setCallback(CallbackData callback) {
    this.callback = callback;
  }


  public BurnItemCallbackRequest gameInventoryId(String gameInventoryId) {
    
    this.gameInventoryId = gameInventoryId;
    return this;
  }

   /**
   * Get gameInventoryId
   * @return gameInventoryId
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_GAME_INVENTORY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGameInventoryId() {
    return gameInventoryId;
  }


  public void setGameInventoryId(String gameInventoryId) {
    this.gameInventoryId = gameInventoryId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurnItemCallbackRequest burnItemCallbackRequest = (BurnItemCallbackRequest) o;
    return Objects.equals(this.callback, burnItemCallbackRequest.callback) &&
        Objects.equals(this.gameInventoryId, burnItemCallbackRequest.gameInventoryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callback, gameInventoryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurnItemCallbackRequest {\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    gameInventoryId: ").append(toIndentedString(gameInventoryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

