/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CreateVirtualCurrencyRequest
 */
@JsonPropertyOrder({
  CreateVirtualCurrencyRequest.JSON_PROPERTY_NAME,
  CreateVirtualCurrencyRequest.JSON_PROPERTY_BASE_CONVERSION,
  CreateVirtualCurrencyRequest.JSON_PROPERTY_FIAT,
  CreateVirtualCurrencyRequest.JSON_PROPERTY_ABBREVIATION,
  CreateVirtualCurrencyRequest.JSON_PROPERTY_BASE_CURRENCY
})
@JsonTypeName("CreateVirtualCurrencyRequest")
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateVirtualCurrencyRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_BASE_CONVERSION = "baseConversion";
  private BigDecimal baseConversion;

  public static final String JSON_PROPERTY_FIAT = "fiat";
  private Boolean fiat;

  public static final String JSON_PROPERTY_ABBREVIATION = "abbreviation";
  private String abbreviation;

  public static final String JSON_PROPERTY_BASE_CURRENCY = "baseCurrency";
  private Boolean baseCurrency;


  public CreateVirtualCurrencyRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "BlankoBucks", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CreateVirtualCurrencyRequest baseConversion(BigDecimal baseConversion) {
    
    this.baseConversion = baseConversion;
    return this;
  }

   /**
   * Get baseConversion
   * @return baseConversion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.25", value = "")
  @JsonProperty(JSON_PROPERTY_BASE_CONVERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getBaseConversion() {
    return baseConversion;
  }


  public void setBaseConversion(BigDecimal baseConversion) {
    this.baseConversion = baseConversion;
  }


  public CreateVirtualCurrencyRequest fiat(Boolean fiat) {
    
    this.fiat = fiat;
    return this;
  }

   /**
   * Get fiat
   * @return fiat
  **/
  @ApiModelProperty(example = "true", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FIAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getFiat() {
    return fiat;
  }


  public void setFiat(Boolean fiat) {
    this.fiat = fiat;
  }


  public CreateVirtualCurrencyRequest abbreviation(String abbreviation) {
    
    this.abbreviation = abbreviation;
    return this;
  }

   /**
   * Get abbreviation
   * @return abbreviation
  **/
  @ApiModelProperty(example = "BB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ABBREVIATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAbbreviation() {
    return abbreviation;
  }


  public void setAbbreviation(String abbreviation) {
    this.abbreviation = abbreviation;
  }


  public CreateVirtualCurrencyRequest baseCurrency(Boolean baseCurrency) {
    
    this.baseCurrency = baseCurrency;
    return this;
  }

   /**
   * Get baseCurrency
   * @return baseCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")
  @JsonProperty(JSON_PROPERTY_BASE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBaseCurrency() {
    return baseCurrency;
  }


  public void setBaseCurrency(Boolean baseCurrency) {
    this.baseCurrency = baseCurrency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVirtualCurrencyRequest createVirtualCurrencyRequest = (CreateVirtualCurrencyRequest) o;
    return Objects.equals(this.name, createVirtualCurrencyRequest.name) &&
        Objects.equals(this.baseConversion, createVirtualCurrencyRequest.baseConversion) &&
        Objects.equals(this.fiat, createVirtualCurrencyRequest.fiat) &&
        Objects.equals(this.abbreviation, createVirtualCurrencyRequest.abbreviation) &&
        Objects.equals(this.baseCurrency, createVirtualCurrencyRequest.baseCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, baseConversion, fiat, abbreviation, baseCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVirtualCurrencyRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    baseConversion: ").append(toIndentedString(baseConversion)).append("\n");
    sb.append("    fiat: ").append(toIndentedString(fiat)).append("\n");
    sb.append("    abbreviation: ").append(toIndentedString(abbreviation)).append("\n");
    sb.append("    baseCurrency: ").append(toIndentedString(baseCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

