/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import games.mythical.ivi.sdk.model.TokenRequestData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * GenerateTokenRequest
 */
@JsonPropertyOrder({
  GenerateTokenRequest.JSON_PROPERTY_TOKEN_REQUEST_DATA
})
@JsonTypeName("GenerateTokenRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GenerateTokenRequest {
  public static final String JSON_PROPERTY_TOKEN_REQUEST_DATA = "tokenRequestData";
  private TokenRequestData tokenRequestData;


  public GenerateTokenRequest tokenRequestData(TokenRequestData tokenRequestData) {
    
    this.tokenRequestData = tokenRequestData;
    return this;
  }

   /**
   * Get tokenRequestData
   * @return tokenRequestData
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_REQUEST_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenRequestData getTokenRequestData() {
    return tokenRequestData;
  }


  public void setTokenRequestData(TokenRequestData tokenRequestData) {
    this.tokenRequestData = tokenRequestData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateTokenRequest generateTokenRequest = (GenerateTokenRequest) o;
    return Objects.equals(this.tokenRequestData, generateTokenRequest.tokenRequestData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenRequestData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateTokenRequest {\n");
    sb.append("    tokenRequestData: ").append(toIndentedString(tokenRequestData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

