/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ItemTypeDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-14T14:31:49.595906-07:00[America/Los_Angeles]")
public class ItemTypeDto {
  public static final String SERIALIZED_NAME_TRANSFERABLE = "transferable";
  @SerializedName(SERIALIZED_NAME_TRANSFERABLE)
  private Boolean transferable;

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "createdTimestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Long createdTimestamp;

  public static final String SERIALIZED_NAME_TOKEN_NAME = "tokenName";
  @SerializedName(SERIALIZED_NAME_TOKEN_NAME)
  private String tokenName;

  public static final String SERIALIZED_NAME_CURRENT_SUPPLY = "currentSupply";
  @SerializedName(SERIALIZED_NAME_CURRENT_SUPPLY)
  private Integer currentSupply;

  public static final String SERIALIZED_NAME_SELLABLE = "sellable";
  @SerializedName(SERIALIZED_NAME_SELLABLE)
  private Boolean sellable;

  public static final String SERIALIZED_NAME_AGREEMENT_IDS = "agreementIds";
  @SerializedName(SERIALIZED_NAME_AGREEMENT_IDS)
  private List<String> agreementIds = null;

  public static final String SERIALIZED_NAME_ISSUER = "issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  private String issuer;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_ISSUE_TIME_SPAN = "issueTimeSpan";
  @SerializedName(SERIALIZED_NAME_ISSUE_TIME_SPAN)
  private Integer issueTimeSpan;

  public static final String SERIALIZED_NAME_FINALIZED = "finalized";
  @SerializedName(SERIALIZED_NAME_FINALIZED)
  private Boolean finalized;

  public static final String SERIALIZED_NAME_ISSUED_SUPPLY = "issuedSupply";
  @SerializedName(SERIALIZED_NAME_ISSUED_SUPPLY)
  private Integer issuedSupply;

  public static final String SERIALIZED_NAME_ENVIRONMENT_ID = "environmentId";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT_ID)
  private String environmentId;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_BASE_URI = "baseUri";
  @SerializedName(SERIALIZED_NAME_BASE_URI)
  private String baseUri;

  public static final String SERIALIZED_NAME_FUNGIBLE = "fungible";
  @SerializedName(SERIALIZED_NAME_FUNGIBLE)
  private Boolean fungible;

  public static final String SERIALIZED_NAME_BURNABLE = "burnable";
  @SerializedName(SERIALIZED_NAME_BURNABLE)
  private Boolean burnable;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_MAX_SUPPLY = "maxSupply";
  @SerializedName(SERIALIZED_NAME_MAX_SUPPLY)
  private Integer maxSupply;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;


  public ItemTypeDto transferable(Boolean transferable) {
    
    this.transferable = transferable;
    return this;
  }

   /**
   * Get transferable
   * @return transferable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTransferable() {
    return transferable;
  }


  public void setTransferable(Boolean transferable) {
    this.transferable = transferable;
  }


  public ItemTypeDto createdTimestamp(Long createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public ItemTypeDto tokenName(String tokenName) {
    
    this.tokenName = tokenName;
    return this;
  }

   /**
   * Get tokenName
   * @return tokenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTokenName() {
    return tokenName;
  }


  public void setTokenName(String tokenName) {
    this.tokenName = tokenName;
  }


  public ItemTypeDto currentSupply(Integer currentSupply) {
    
    this.currentSupply = currentSupply;
    return this;
  }

   /**
   * Get currentSupply
   * @return currentSupply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCurrentSupply() {
    return currentSupply;
  }


  public void setCurrentSupply(Integer currentSupply) {
    this.currentSupply = currentSupply;
  }


  public ItemTypeDto sellable(Boolean sellable) {
    
    this.sellable = sellable;
    return this;
  }

   /**
   * Get sellable
   * @return sellable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSellable() {
    return sellable;
  }


  public void setSellable(Boolean sellable) {
    this.sellable = sellable;
  }


  public ItemTypeDto agreementIds(List<String> agreementIds) {
    
    this.agreementIds = agreementIds;
    return this;
  }

  public ItemTypeDto addAgreementIdsItem(String agreementIdsItem) {
    if (this.agreementIds == null) {
      this.agreementIds = new ArrayList<String>();
    }
    this.agreementIds.add(agreementIdsItem);
    return this;
  }

   /**
   * Get agreementIds
   * @return agreementIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAgreementIds() {
    return agreementIds;
  }


  public void setAgreementIds(List<String> agreementIds) {
    this.agreementIds = agreementIds;
  }


  public ItemTypeDto issuer(String issuer) {
    
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIssuer() {
    return issuer;
  }


  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }


  public ItemTypeDto transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public ItemTypeDto issueTimeSpan(Integer issueTimeSpan) {
    
    this.issueTimeSpan = issueTimeSpan;
    return this;
  }

   /**
   * Get issueTimeSpan
   * @return issueTimeSpan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getIssueTimeSpan() {
    return issueTimeSpan;
  }


  public void setIssueTimeSpan(Integer issueTimeSpan) {
    this.issueTimeSpan = issueTimeSpan;
  }


  public ItemTypeDto finalized(Boolean finalized) {
    
    this.finalized = finalized;
    return this;
  }

   /**
   * Get finalized
   * @return finalized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFinalized() {
    return finalized;
  }


  public void setFinalized(Boolean finalized) {
    this.finalized = finalized;
  }


  public ItemTypeDto issuedSupply(Integer issuedSupply) {
    
    this.issuedSupply = issuedSupply;
    return this;
  }

   /**
   * Get issuedSupply
   * @return issuedSupply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getIssuedSupply() {
    return issuedSupply;
  }


  public void setIssuedSupply(Integer issuedSupply) {
    this.issuedSupply = issuedSupply;
  }


  public ItemTypeDto environmentId(String environmentId) {
    
    this.environmentId = environmentId;
    return this;
  }

   /**
   * Get environmentId
   * @return environmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEnvironmentId() {
    return environmentId;
  }


  public void setEnvironmentId(String environmentId) {
    this.environmentId = environmentId;
  }


  public ItemTypeDto createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public ItemTypeDto baseUri(String baseUri) {
    
    this.baseUri = baseUri;
    return this;
  }

   /**
   * Get baseUri
   * @return baseUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBaseUri() {
    return baseUri;
  }


  public void setBaseUri(String baseUri) {
    this.baseUri = baseUri;
  }


  public ItemTypeDto fungible(Boolean fungible) {
    
    this.fungible = fungible;
    return this;
  }

   /**
   * Get fungible
   * @return fungible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFungible() {
    return fungible;
  }


  public void setFungible(Boolean fungible) {
    this.fungible = fungible;
  }


  public ItemTypeDto burnable(Boolean burnable) {
    
    this.burnable = burnable;
    return this;
  }

   /**
   * Get burnable
   * @return burnable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBurnable() {
    return burnable;
  }


  public void setBurnable(Boolean burnable) {
    this.burnable = burnable;
  }


  public ItemTypeDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ItemTypeDto maxSupply(Integer maxSupply) {
    
    this.maxSupply = maxSupply;
    return this;
  }

   /**
   * Get maxSupply
   * @return maxSupply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxSupply() {
    return maxSupply;
  }


  public void setMaxSupply(Integer maxSupply) {
    this.maxSupply = maxSupply;
  }


  public ItemTypeDto category(String category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCategory() {
    return category;
  }


  public void setCategory(String category) {
    this.category = category;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemTypeDto itemTypeDto = (ItemTypeDto) o;
    return Objects.equals(this.transferable, itemTypeDto.transferable) &&
        Objects.equals(this.createdTimestamp, itemTypeDto.createdTimestamp) &&
        Objects.equals(this.tokenName, itemTypeDto.tokenName) &&
        Objects.equals(this.currentSupply, itemTypeDto.currentSupply) &&
        Objects.equals(this.sellable, itemTypeDto.sellable) &&
        Objects.equals(this.agreementIds, itemTypeDto.agreementIds) &&
        Objects.equals(this.issuer, itemTypeDto.issuer) &&
        Objects.equals(this.transactionId, itemTypeDto.transactionId) &&
        Objects.equals(this.issueTimeSpan, itemTypeDto.issueTimeSpan) &&
        Objects.equals(this.finalized, itemTypeDto.finalized) &&
        Objects.equals(this.issuedSupply, itemTypeDto.issuedSupply) &&
        Objects.equals(this.environmentId, itemTypeDto.environmentId) &&
        Objects.equals(this.createdBy, itemTypeDto.createdBy) &&
        Objects.equals(this.baseUri, itemTypeDto.baseUri) &&
        Objects.equals(this.fungible, itemTypeDto.fungible) &&
        Objects.equals(this.burnable, itemTypeDto.burnable) &&
        Objects.equals(this.id, itemTypeDto.id) &&
        Objects.equals(this.maxSupply, itemTypeDto.maxSupply) &&
        Objects.equals(this.category, itemTypeDto.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferable, createdTimestamp, tokenName, currentSupply, sellable, agreementIds, issuer, transactionId, issueTimeSpan, finalized, issuedSupply, environmentId, createdBy, baseUri, fungible, burnable, id, maxSupply, category);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemTypeDto {\n");
    sb.append("    transferable: ").append(toIndentedString(transferable)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    currentSupply: ").append(toIndentedString(currentSupply)).append("\n");
    sb.append("    sellable: ").append(toIndentedString(sellable)).append("\n");
    sb.append("    agreementIds: ").append(toIndentedString(agreementIds)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    issueTimeSpan: ").append(toIndentedString(issueTimeSpan)).append("\n");
    sb.append("    finalized: ").append(toIndentedString(finalized)).append("\n");
    sb.append("    issuedSupply: ").append(toIndentedString(issuedSupply)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    baseUri: ").append(toIndentedString(baseUri)).append("\n");
    sb.append("    fungible: ").append(toIndentedString(fungible)).append("\n");
    sb.append("    burnable: ").append(toIndentedString(burnable)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maxSupply: ").append(toIndentedString(maxSupply)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

