/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ListingDto
 */
@JsonPropertyOrder({
  ListingDto.JSON_PROPERTY_SALE_AMOUNT,
  ListingDto.JSON_PROPERTY_CURRENCY_BASE,
  ListingDto.JSON_PROPERTY_TRANSACTION_ID_CLOSED,
  ListingDto.JSON_PROPERTY_SELL_BY_DAYS,
  ListingDto.JSON_PROPERTY_CREATED_TIMESTAMP,
  ListingDto.JSON_PROPERTY_SELLER_PLAYER_ID,
  ListingDto.JSON_PROPERTY_FINALIZED_CLOSED,
  ListingDto.JSON_PROPERTY_BATCH_ID,
  ListingDto.JSON_PROPERTY_TRANSACTION_ID,
  ListingDto.JSON_PROPERTY_FINALIZED,
  ListingDto.JSON_PROPERTY_SELL_BY_DATE,
  ListingDto.JSON_PROPERTY_ENVIRONMENT_ID,
  ListingDto.JSON_PROPERTY_CREATED_BY,
  ListingDto.JSON_PROPERTY_SALE_MODEL,
  ListingDto.JSON_PROPERTY_GAME_INVENTORY_IDS,
  ListingDto.JSON_PROPERTY_CLOSED,
  ListingDto.JSON_PROPERTY_CURRENCY,
  ListingDto.JSON_PROPERTY_DGOOD_IDS,
  ListingDto.JSON_PROPERTY_SALE_AMOUNT_BASE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-15T00:53:22.361116-07:00[America/Los_Angeles]")
public class ListingDto {
  public static final String JSON_PROPERTY_SALE_AMOUNT = "saleAmount";
  private BigDecimal saleAmount;

  public static final String JSON_PROPERTY_CURRENCY_BASE = "currencyBase";
  private String currencyBase;

  public static final String JSON_PROPERTY_TRANSACTION_ID_CLOSED = "transactionIdClosed";
  private String transactionIdClosed;

  public static final String JSON_PROPERTY_SELL_BY_DAYS = "sellByDays";
  private Integer sellByDays;

  public static final String JSON_PROPERTY_CREATED_TIMESTAMP = "createdTimestamp";
  private Long createdTimestamp;

  public static final String JSON_PROPERTY_SELLER_PLAYER_ID = "sellerPlayerId";
  private String sellerPlayerId;

  public static final String JSON_PROPERTY_FINALIZED_CLOSED = "finalizedClosed";
  private Boolean finalizedClosed;

  public static final String JSON_PROPERTY_BATCH_ID = "batchId";
  private Long batchId;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  private String transactionId;

  public static final String JSON_PROPERTY_FINALIZED = "finalized";
  private Boolean finalized;

  public static final String JSON_PROPERTY_SELL_BY_DATE = "sellByDate";
  private Long sellByDate;

  public static final String JSON_PROPERTY_ENVIRONMENT_ID = "environmentId";
  private String environmentId;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  /**
   * Gets or Sets saleModel
   */
  public enum SaleModelEnum {
    FIXED_PRICE("FIXED_PRICE"),
    
    UNRECOGNIZED("UNRECOGNIZED");

    private String value;

    SaleModelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SaleModelEnum fromValue(String value) {
      for (SaleModelEnum b : SaleModelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SALE_MODEL = "saleModel";
  private SaleModelEnum saleModel;

  public static final String JSON_PROPERTY_GAME_INVENTORY_IDS = "gameInventoryIds";
  private List<String> gameInventoryIds = null;

  public static final String JSON_PROPERTY_CLOSED = "closed";
  private Boolean closed;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_DGOOD_IDS = "dgoodIds";
  private List<Long> dgoodIds = null;

  public static final String JSON_PROPERTY_SALE_AMOUNT_BASE = "saleAmountBase";
  private BigDecimal saleAmountBase;


  public ListingDto saleAmount(BigDecimal saleAmount) {
    
    this.saleAmount = saleAmount;
    return this;
  }

   /**
   * Get saleAmount
   * @return saleAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSaleAmount() {
    return saleAmount;
  }


  public void setSaleAmount(BigDecimal saleAmount) {
    this.saleAmount = saleAmount;
  }


  public ListingDto currencyBase(String currencyBase) {
    
    this.currencyBase = currencyBase;
    return this;
  }

   /**
   * Get currencyBase
   * @return currencyBase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrencyBase() {
    return currencyBase;
  }


  public void setCurrencyBase(String currencyBase) {
    this.currencyBase = currencyBase;
  }


  public ListingDto transactionIdClosed(String transactionIdClosed) {
    
    this.transactionIdClosed = transactionIdClosed;
    return this;
  }

   /**
   * Get transactionIdClosed
   * @return transactionIdClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionIdClosed() {
    return transactionIdClosed;
  }


  public void setTransactionIdClosed(String transactionIdClosed) {
    this.transactionIdClosed = transactionIdClosed;
  }


  public ListingDto sellByDays(Integer sellByDays) {
    
    this.sellByDays = sellByDays;
    return this;
  }

   /**
   * Get sellByDays
   * @return sellByDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SELL_BY_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSellByDays() {
    return sellByDays;
  }


  public void setSellByDays(Integer sellByDays) {
    this.sellByDays = sellByDays;
  }


  public ListingDto createdTimestamp(Long createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public ListingDto sellerPlayerId(String sellerPlayerId) {
    
    this.sellerPlayerId = sellerPlayerId;
    return this;
  }

   /**
   * Get sellerPlayerId
   * @return sellerPlayerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SELLER_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSellerPlayerId() {
    return sellerPlayerId;
  }


  public void setSellerPlayerId(String sellerPlayerId) {
    this.sellerPlayerId = sellerPlayerId;
  }


  public ListingDto finalizedClosed(Boolean finalizedClosed) {
    
    this.finalizedClosed = finalizedClosed;
    return this;
  }

   /**
   * Get finalizedClosed
   * @return finalizedClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FINALIZED_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFinalizedClosed() {
    return finalizedClosed;
  }


  public void setFinalizedClosed(Boolean finalizedClosed) {
    this.finalizedClosed = finalizedClosed;
  }


  public ListingDto batchId(Long batchId) {
    
    this.batchId = batchId;
    return this;
  }

   /**
   * Get batchId
   * @return batchId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBatchId() {
    return batchId;
  }


  public void setBatchId(Long batchId) {
    this.batchId = batchId;
  }


  public ListingDto transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public ListingDto finalized(Boolean finalized) {
    
    this.finalized = finalized;
    return this;
  }

   /**
   * Get finalized
   * @return finalized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FINALIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFinalized() {
    return finalized;
  }


  public void setFinalized(Boolean finalized) {
    this.finalized = finalized;
  }


  public ListingDto sellByDate(Long sellByDate) {
    
    this.sellByDate = sellByDate;
    return this;
  }

   /**
   * Get sellByDate
   * @return sellByDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SELL_BY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSellByDate() {
    return sellByDate;
  }


  public void setSellByDate(Long sellByDate) {
    this.sellByDate = sellByDate;
  }


  public ListingDto environmentId(String environmentId) {
    
    this.environmentId = environmentId;
    return this;
  }

   /**
   * Get environmentId
   * @return environmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnvironmentId() {
    return environmentId;
  }


  public void setEnvironmentId(String environmentId) {
    this.environmentId = environmentId;
  }


  public ListingDto createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public ListingDto saleModel(SaleModelEnum saleModel) {
    
    this.saleModel = saleModel;
    return this;
  }

   /**
   * Get saleModel
   * @return saleModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALE_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SaleModelEnum getSaleModel() {
    return saleModel;
  }


  public void setSaleModel(SaleModelEnum saleModel) {
    this.saleModel = saleModel;
  }


  public ListingDto gameInventoryIds(List<String> gameInventoryIds) {
    
    this.gameInventoryIds = gameInventoryIds;
    return this;
  }

  public ListingDto addGameInventoryIdsItem(String gameInventoryIdsItem) {
    if (this.gameInventoryIds == null) {
      this.gameInventoryIds = new ArrayList<>();
    }
    this.gameInventoryIds.add(gameInventoryIdsItem);
    return this;
  }

   /**
   * Get gameInventoryIds
   * @return gameInventoryIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GAME_INVENTORY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGameInventoryIds() {
    return gameInventoryIds;
  }


  public void setGameInventoryIds(List<String> gameInventoryIds) {
    this.gameInventoryIds = gameInventoryIds;
  }


  public ListingDto closed(Boolean closed) {
    
    this.closed = closed;
    return this;
  }

   /**
   * Get closed
   * @return closed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getClosed() {
    return closed;
  }


  public void setClosed(Boolean closed) {
    this.closed = closed;
  }


  public ListingDto currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public ListingDto dgoodIds(List<Long> dgoodIds) {
    
    this.dgoodIds = dgoodIds;
    return this;
  }

  public ListingDto addDgoodIdsItem(Long dgoodIdsItem) {
    if (this.dgoodIds == null) {
      this.dgoodIds = new ArrayList<>();
    }
    this.dgoodIds.add(dgoodIdsItem);
    return this;
  }

   /**
   * Get dgoodIds
   * @return dgoodIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DGOOD_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getDgoodIds() {
    return dgoodIds;
  }


  public void setDgoodIds(List<Long> dgoodIds) {
    this.dgoodIds = dgoodIds;
  }


  public ListingDto saleAmountBase(BigDecimal saleAmountBase) {
    
    this.saleAmountBase = saleAmountBase;
    return this;
  }

   /**
   * Get saleAmountBase
   * @return saleAmountBase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALE_AMOUNT_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSaleAmountBase() {
    return saleAmountBase;
  }


  public void setSaleAmountBase(BigDecimal saleAmountBase) {
    this.saleAmountBase = saleAmountBase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingDto listingDto = (ListingDto) o;
    return Objects.equals(this.saleAmount, listingDto.saleAmount) &&
        Objects.equals(this.currencyBase, listingDto.currencyBase) &&
        Objects.equals(this.transactionIdClosed, listingDto.transactionIdClosed) &&
        Objects.equals(this.sellByDays, listingDto.sellByDays) &&
        Objects.equals(this.createdTimestamp, listingDto.createdTimestamp) &&
        Objects.equals(this.sellerPlayerId, listingDto.sellerPlayerId) &&
        Objects.equals(this.finalizedClosed, listingDto.finalizedClosed) &&
        Objects.equals(this.batchId, listingDto.batchId) &&
        Objects.equals(this.transactionId, listingDto.transactionId) &&
        Objects.equals(this.finalized, listingDto.finalized) &&
        Objects.equals(this.sellByDate, listingDto.sellByDate) &&
        Objects.equals(this.environmentId, listingDto.environmentId) &&
        Objects.equals(this.createdBy, listingDto.createdBy) &&
        Objects.equals(this.saleModel, listingDto.saleModel) &&
        Objects.equals(this.gameInventoryIds, listingDto.gameInventoryIds) &&
        Objects.equals(this.closed, listingDto.closed) &&
        Objects.equals(this.currency, listingDto.currency) &&
        Objects.equals(this.dgoodIds, listingDto.dgoodIds) &&
        Objects.equals(this.saleAmountBase, listingDto.saleAmountBase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleAmount, currencyBase, transactionIdClosed, sellByDays, createdTimestamp, sellerPlayerId, finalizedClosed, batchId, transactionId, finalized, sellByDate, environmentId, createdBy, saleModel, gameInventoryIds, closed, currency, dgoodIds, saleAmountBase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingDto {\n");
    sb.append("    saleAmount: ").append(toIndentedString(saleAmount)).append("\n");
    sb.append("    currencyBase: ").append(toIndentedString(currencyBase)).append("\n");
    sb.append("    transactionIdClosed: ").append(toIndentedString(transactionIdClosed)).append("\n");
    sb.append("    sellByDays: ").append(toIndentedString(sellByDays)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    sellerPlayerId: ").append(toIndentedString(sellerPlayerId)).append("\n");
    sb.append("    finalizedClosed: ").append(toIndentedString(finalizedClosed)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    finalized: ").append(toIndentedString(finalized)).append("\n");
    sb.append("    sellByDate: ").append(toIndentedString(sellByDate)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    saleModel: ").append(toIndentedString(saleModel)).append("\n");
    sb.append("    gameInventoryIds: ").append(toIndentedString(gameInventoryIds)).append("\n");
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    dgoodIds: ").append(toIndentedString(dgoodIds)).append("\n");
    sb.append("    saleAmountBase: ").append(toIndentedString(saleAmountBase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

