/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MarketplaceItemDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-14T14:31:49.595906-07:00[America/Los_Angeles]")
public class MarketplaceItemDto {
  public static final String SERIALIZED_NAME_DGOODS_METADATA = "dgoodsMetadata";
  @SerializedName(SERIALIZED_NAME_DGOODS_METADATA)
  private String dgoodsMetadata;

  public static final String SERIALIZED_NAME_IMAGE_LARGE_URL = "imageLargeUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_LARGE_URL)
  private String imageLargeUrl;

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "createdTimestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Long createdTimestamp;

  public static final String SERIALIZED_NAME_TOKEN_NAME = "tokenName";
  @SerializedName(SERIALIZED_NAME_TOKEN_NAME)
  private String tokenName;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LISTING_ID = "listingId";
  @SerializedName(SERIALIZED_NAME_LISTING_ID)
  private String listingId;

  public static final String SERIALIZED_NAME_IMAGE_SMALL_URL = "imageSmallUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_SMALL_URL)
  private String imageSmallUrl;

  public static final String SERIALIZED_NAME_METADATA_URI = "metadataUri";
  @SerializedName(SERIALIZED_NAME_METADATA_URI)
  private String metadataUri;

  public static final String SERIALIZED_NAME_GAME_INVENTORY_ID = "gameInventoryId";
  @SerializedName(SERIALIZED_NAME_GAME_INVENTORY_ID)
  private String gameInventoryId;

  public static final String SERIALIZED_NAME_OWNER_MYTHICAL_ID = "ownerMythicalId";
  @SerializedName(SERIALIZED_NAME_OWNER_MYTHICAL_ID)
  private String ownerMythicalId;

  public static final String SERIALIZED_NAME_FINALIZED = "finalized";
  @SerializedName(SERIALIZED_NAME_FINALIZED)
  private Boolean finalized;

  public static final String SERIALIZED_NAME_ITEM_NAME = "itemName";
  @SerializedName(SERIALIZED_NAME_ITEM_NAME)
  private String itemName;

  public static final String SERIALIZED_NAME_OWNER_PLAYER_ID = "ownerPlayerId";
  @SerializedName(SERIALIZED_NAME_OWNER_PLAYER_ID)
  private String ownerPlayerId;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public static final String SERIALIZED_NAME_RENDER = "render";
  @SerializedName(SERIALIZED_NAME_RENDER)
  private String render;

  public static final String SERIALIZED_NAME_DGOOD_ID = "dgoodId";
  @SerializedName(SERIALIZED_NAME_DGOOD_ID)
  private Long dgoodId;


  public MarketplaceItemDto dgoodsMetadata(String dgoodsMetadata) {
    
    this.dgoodsMetadata = dgoodsMetadata;
    return this;
  }

   /**
   * Get dgoodsMetadata
   * @return dgoodsMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDgoodsMetadata() {
    return dgoodsMetadata;
  }


  public void setDgoodsMetadata(String dgoodsMetadata) {
    this.dgoodsMetadata = dgoodsMetadata;
  }


  public MarketplaceItemDto imageLargeUrl(String imageLargeUrl) {
    
    this.imageLargeUrl = imageLargeUrl;
    return this;
  }

   /**
   * Get imageLargeUrl
   * @return imageLargeUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImageLargeUrl() {
    return imageLargeUrl;
  }


  public void setImageLargeUrl(String imageLargeUrl) {
    this.imageLargeUrl = imageLargeUrl;
  }


  public MarketplaceItemDto createdTimestamp(Long createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * Get createdTimestamp
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public MarketplaceItemDto tokenName(String tokenName) {
    
    this.tokenName = tokenName;
    return this;
  }

   /**
   * Get tokenName
   * @return tokenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTokenName() {
    return tokenName;
  }


  public void setTokenName(String tokenName) {
    this.tokenName = tokenName;
  }


  public MarketplaceItemDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public MarketplaceItemDto listingId(String listingId) {
    
    this.listingId = listingId;
    return this;
  }

   /**
   * Get listingId
   * @return listingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getListingId() {
    return listingId;
  }


  public void setListingId(String listingId) {
    this.listingId = listingId;
  }


  public MarketplaceItemDto imageSmallUrl(String imageSmallUrl) {
    
    this.imageSmallUrl = imageSmallUrl;
    return this;
  }

   /**
   * Get imageSmallUrl
   * @return imageSmallUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImageSmallUrl() {
    return imageSmallUrl;
  }


  public void setImageSmallUrl(String imageSmallUrl) {
    this.imageSmallUrl = imageSmallUrl;
  }


  public MarketplaceItemDto metadataUri(String metadataUri) {
    
    this.metadataUri = metadataUri;
    return this;
  }

   /**
   * Get metadataUri
   * @return metadataUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMetadataUri() {
    return metadataUri;
  }


  public void setMetadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
  }


  public MarketplaceItemDto gameInventoryId(String gameInventoryId) {
    
    this.gameInventoryId = gameInventoryId;
    return this;
  }

   /**
   * Get gameInventoryId
   * @return gameInventoryId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGameInventoryId() {
    return gameInventoryId;
  }


  public void setGameInventoryId(String gameInventoryId) {
    this.gameInventoryId = gameInventoryId;
  }


  public MarketplaceItemDto ownerMythicalId(String ownerMythicalId) {
    
    this.ownerMythicalId = ownerMythicalId;
    return this;
  }

   /**
   * Get ownerMythicalId
   * @return ownerMythicalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOwnerMythicalId() {
    return ownerMythicalId;
  }


  public void setOwnerMythicalId(String ownerMythicalId) {
    this.ownerMythicalId = ownerMythicalId;
  }


  public MarketplaceItemDto finalized(Boolean finalized) {
    
    this.finalized = finalized;
    return this;
  }

   /**
   * Get finalized
   * @return finalized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getFinalized() {
    return finalized;
  }


  public void setFinalized(Boolean finalized) {
    this.finalized = finalized;
  }


  public MarketplaceItemDto itemName(String itemName) {
    
    this.itemName = itemName;
    return this;
  }

   /**
   * Get itemName
   * @return itemName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemName() {
    return itemName;
  }


  public void setItemName(String itemName) {
    this.itemName = itemName;
  }


  public MarketplaceItemDto ownerPlayerId(String ownerPlayerId) {
    
    this.ownerPlayerId = ownerPlayerId;
    return this;
  }

   /**
   * Get ownerPlayerId
   * @return ownerPlayerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOwnerPlayerId() {
    return ownerPlayerId;
  }


  public void setOwnerPlayerId(String ownerPlayerId) {
    this.ownerPlayerId = ownerPlayerId;
  }


  public MarketplaceItemDto category(String category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCategory() {
    return category;
  }


  public void setCategory(String category) {
    this.category = category;
  }


  public MarketplaceItemDto render(String render) {
    
    this.render = render;
    return this;
  }

   /**
   * Get render
   * @return render
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRender() {
    return render;
  }


  public void setRender(String render) {
    this.render = render;
  }


  public MarketplaceItemDto dgoodId(Long dgoodId) {
    
    this.dgoodId = dgoodId;
    return this;
  }

   /**
   * Get dgoodId
   * @return dgoodId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDgoodId() {
    return dgoodId;
  }


  public void setDgoodId(Long dgoodId) {
    this.dgoodId = dgoodId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplaceItemDto marketplaceItemDto = (MarketplaceItemDto) o;
    return Objects.equals(this.dgoodsMetadata, marketplaceItemDto.dgoodsMetadata) &&
        Objects.equals(this.imageLargeUrl, marketplaceItemDto.imageLargeUrl) &&
        Objects.equals(this.createdTimestamp, marketplaceItemDto.createdTimestamp) &&
        Objects.equals(this.tokenName, marketplaceItemDto.tokenName) &&
        Objects.equals(this.description, marketplaceItemDto.description) &&
        Objects.equals(this.listingId, marketplaceItemDto.listingId) &&
        Objects.equals(this.imageSmallUrl, marketplaceItemDto.imageSmallUrl) &&
        Objects.equals(this.metadataUri, marketplaceItemDto.metadataUri) &&
        Objects.equals(this.gameInventoryId, marketplaceItemDto.gameInventoryId) &&
        Objects.equals(this.ownerMythicalId, marketplaceItemDto.ownerMythicalId) &&
        Objects.equals(this.finalized, marketplaceItemDto.finalized) &&
        Objects.equals(this.itemName, marketplaceItemDto.itemName) &&
        Objects.equals(this.ownerPlayerId, marketplaceItemDto.ownerPlayerId) &&
        Objects.equals(this.category, marketplaceItemDto.category) &&
        Objects.equals(this.render, marketplaceItemDto.render) &&
        Objects.equals(this.dgoodId, marketplaceItemDto.dgoodId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dgoodsMetadata, imageLargeUrl, createdTimestamp, tokenName, description, listingId, imageSmallUrl, metadataUri, gameInventoryId, ownerMythicalId, finalized, itemName, ownerPlayerId, category, render, dgoodId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplaceItemDto {\n");
    sb.append("    dgoodsMetadata: ").append(toIndentedString(dgoodsMetadata)).append("\n");
    sb.append("    imageLargeUrl: ").append(toIndentedString(imageLargeUrl)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    listingId: ").append(toIndentedString(listingId)).append("\n");
    sb.append("    imageSmallUrl: ").append(toIndentedString(imageSmallUrl)).append("\n");
    sb.append("    metadataUri: ").append(toIndentedString(metadataUri)).append("\n");
    sb.append("    gameInventoryId: ").append(toIndentedString(gameInventoryId)).append("\n");
    sb.append("    ownerMythicalId: ").append(toIndentedString(ownerMythicalId)).append("\n");
    sb.append("    finalized: ").append(toIndentedString(finalized)).append("\n");
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    ownerPlayerId: ").append(toIndentedString(ownerPlayerId)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    render: ").append(toIndentedString(render)).append("\n");
    sb.append("    dgoodId: ").append(toIndentedString(dgoodId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

