/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import games.mythical.ivi.sdk.model.BitPayOrderRequestData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * OrderRequestProviderData
 */
@JsonPropertyOrder({
  OrderRequestProviderData.JSON_PROPERTY_BITPAY
})
@JsonTypeName("OrderRequestProviderData")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrderRequestProviderData {
  public static final String JSON_PROPERTY_BITPAY = "bitpay";
  private BitPayOrderRequestData bitpay;


  public OrderRequestProviderData bitpay(BitPayOrderRequestData bitpay) {
    
    this.bitpay = bitpay;
    return this;
  }

   /**
   * Get bitpay
   * @return bitpay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BITPAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BitPayOrderRequestData getBitpay() {
    return bitpay;
  }


  public void setBitpay(BitPayOrderRequestData bitpay) {
    this.bitpay = bitpay;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRequestProviderData orderRequestProviderData = (OrderRequestProviderData) o;
    return Objects.equals(this.bitpay, orderRequestProviderData.bitpay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitpay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequestProviderData {\n");
    sb.append("    bitpay: ").append(toIndentedString(bitpay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

