/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: unspecified
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SalesTaxTransactionDto
 */
@JsonPropertyOrder({
  SalesTaxTransactionDto.JSON_PROPERTY_TRANSACTION_DATE,
  SalesTaxTransactionDto.JSON_PROPERTY_TO_ZIP,
  SalesTaxTransactionDto.JSON_PROPERTY_TAXABLE_AMOUNT,
  SalesTaxTransactionDto.JSON_PROPERTY_TO_STATE,
  SalesTaxTransactionDto.JSON_PROPERTY_SALES_TAX_AMOUNT,
  SalesTaxTransactionDto.JSON_PROPERTY_TO_CITY,
  SalesTaxTransactionDto.JSON_PROPERTY_USER_ID,
  SalesTaxTransactionDto.JSON_PROPERTY_TRANSACTION_ID,
  SalesTaxTransactionDto.JSON_PROPERTY_TO_COUNTRY
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-15T09:19:26.551556-07:00[America/Los_Angeles]")
public class SalesTaxTransactionDto {
  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transaction_date";
  private Long transactionDate;

  public static final String JSON_PROPERTY_TO_ZIP = "toZip";
  private String toZip;

  public static final String JSON_PROPERTY_TAXABLE_AMOUNT = "taxableAmount";
  private BigDecimal taxableAmount;

  public static final String JSON_PROPERTY_TO_STATE = "toState";
  private String toState;

  public static final String JSON_PROPERTY_SALES_TAX_AMOUNT = "salesTaxAmount";
  private BigDecimal salesTaxAmount;

  public static final String JSON_PROPERTY_TO_CITY = "toCity";
  private String toCity;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private Integer userId;

  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  private String transactionId;

  public static final String JSON_PROPERTY_TO_COUNTRY = "toCountry";
  private String toCountry;


  public SalesTaxTransactionDto transactionDate(Long transactionDate) {
    
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Get transactionDate
   * @return transactionDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTransactionDate() {
    return transactionDate;
  }


  public void setTransactionDate(Long transactionDate) {
    this.transactionDate = transactionDate;
  }


  public SalesTaxTransactionDto toZip(String toZip) {
    
    this.toZip = toZip;
    return this;
  }

   /**
   * Get toZip
   * @return toZip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToZip() {
    return toZip;
  }


  public void setToZip(String toZip) {
    this.toZip = toZip;
  }


  public SalesTaxTransactionDto taxableAmount(BigDecimal taxableAmount) {
    
    this.taxableAmount = taxableAmount;
    return this;
  }

   /**
   * Get taxableAmount
   * @return taxableAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAXABLE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTaxableAmount() {
    return taxableAmount;
  }


  public void setTaxableAmount(BigDecimal taxableAmount) {
    this.taxableAmount = taxableAmount;
  }


  public SalesTaxTransactionDto toState(String toState) {
    
    this.toState = toState;
    return this;
  }

   /**
   * Get toState
   * @return toState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToState() {
    return toState;
  }


  public void setToState(String toState) {
    this.toState = toState;
  }


  public SalesTaxTransactionDto salesTaxAmount(BigDecimal salesTaxAmount) {
    
    this.salesTaxAmount = salesTaxAmount;
    return this;
  }

   /**
   * Get salesTaxAmount
   * @return salesTaxAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SALES_TAX_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSalesTaxAmount() {
    return salesTaxAmount;
  }


  public void setSalesTaxAmount(BigDecimal salesTaxAmount) {
    this.salesTaxAmount = salesTaxAmount;
  }


  public SalesTaxTransactionDto toCity(String toCity) {
    
    this.toCity = toCity;
    return this;
  }

   /**
   * Get toCity
   * @return toCity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToCity() {
    return toCity;
  }


  public void setToCity(String toCity) {
    this.toCity = toCity;
  }


  public SalesTaxTransactionDto userId(Integer userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public SalesTaxTransactionDto transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public SalesTaxTransactionDto toCountry(String toCountry) {
    
    this.toCountry = toCountry;
    return this;
  }

   /**
   * Get toCountry
   * @return toCountry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToCountry() {
    return toCountry;
  }


  public void setToCountry(String toCountry) {
    this.toCountry = toCountry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesTaxTransactionDto salesTaxTransactionDto = (SalesTaxTransactionDto) o;
    return Objects.equals(this.transactionDate, salesTaxTransactionDto.transactionDate) &&
        Objects.equals(this.toZip, salesTaxTransactionDto.toZip) &&
        Objects.equals(this.taxableAmount, salesTaxTransactionDto.taxableAmount) &&
        Objects.equals(this.toState, salesTaxTransactionDto.toState) &&
        Objects.equals(this.salesTaxAmount, salesTaxTransactionDto.salesTaxAmount) &&
        Objects.equals(this.toCity, salesTaxTransactionDto.toCity) &&
        Objects.equals(this.userId, salesTaxTransactionDto.userId) &&
        Objects.equals(this.transactionId, salesTaxTransactionDto.transactionId) &&
        Objects.equals(this.toCountry, salesTaxTransactionDto.toCountry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionDate, toZip, taxableAmount, toState, salesTaxAmount, toCity, userId, transactionId, toCountry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesTaxTransactionDto {\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    toZip: ").append(toIndentedString(toZip)).append("\n");
    sb.append("    taxableAmount: ").append(toIndentedString(taxableAmount)).append("\n");
    sb.append("    toState: ").append(toIndentedString(toState)).append("\n");
    sb.append("    salesTaxAmount: ").append(toIndentedString(salesTaxAmount)).append("\n");
    sb.append("    toCity: ").append(toIndentedString(toCity)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    toCountry: ").append(toIndentedString(toCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

