package games.mythical.ivi.sdk.exception;

public enum IVIErrorCode {
    ENVIRONMENT_ID_NOT_SET,
    APIKEY_NOT_SET,
    HOST_NOT_SET,
    PORT_NOT_SET,
    NOT_FOUND,
    LOCAL_EXCEPTION,
    PARSING_DATA_EXCEPTION,
    UNKNOWN_GRPC_ERROR,
    SERVER_ERROR,
    OUT_OF_RANGE,
    DEADLINE_EXCEEDED,
    ALREADY_EXISTS,
    PERMISSION_DENIED,
    UNIMPLEMENTED,
    UNAUTHENTICATED,
    UNAVAILABLE,
    INTERNAL,
    RESOURCE_EXHAUSTED,
    ABORTED,
    DATA_LOSS,
    INVALID_ARGUMENT,
    FAILED_PRECONDITION
}
