/*
 * IVI Engine
 * IVI Engine
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: developer@mythical.games
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package games.mythical.ivi.sdk.api;

import games.mythical.ivi.sdk.model.ThemeDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserSettingsApi
 */
@Ignore
public class UserSettingsApiTest {

    private final UserSettingsApi api = new UserSettingsApi();

    
    /**
     * Get the display theme
     *
     * Returns the user&#39;s preferred display theme: DARK or LIGHT.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getThemeTest() {
        ThemeDto response = api.getTheme();

        // TODO: test validations
    }
    
    /**
     * Set the display theme
     *
     * Set the user&#39;s preferred display theme: DARK or LIGHT.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setThemeTest() {
        String body = null;
        api.setTheme(body);

        // TODO: test validations
    }
    
    /**
     * Update the display theme
     *
     * Update the user&#39;s preferred display theme: DARK or LIGHT.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateThemeTest() {
        String body = null;
        api.updateTheme(body);

        // TODO: test validations
    }
    
}
